edisonrmedina/GreenLand

- client/README.md
"Se agregó un README detallado que describe nuestro proyecto de ecommerce ecológico. Incluye información sobre la visión, tecnologías utilizadas en el frontend y backend, así como las instrucciones para configurar el entorno local y levantar la aplicación. Se adjuntaron imágenes para ilustrar los componentes clave del proyecto. ¡Esperamos sus comentarios y sugerencias para seguir mejorando este proyecto!"
> actualizando el README

- client/src/App.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/NavBar/ppruebita.txt
> subvri pruebita

- api/src/database/config.js
- api/src/models/DetailOrder.js
- api/src/models/Order.js
- api/src/models/Review.js
- api/src/models/User.js
- api/src/server.js
Se agregan los modelos restantes tales como: Order, DetailOrder y review, y las relaciones uno a muchos y muchos a muchos
> Add last models and relations

- client/src/App.jsx
- client/src/components/NavBar/NavBar.module.css
- client/src/components/Product/Product.jsx
- client/src/components/Product/Product.module.css
- client/src/components/Products/Products.jsx
- client/src/components/Products/Products.module.css
product grid, add product and products components
> products cards implementation

- client/src/App.css
- client/src/components/NavBar/NavBar.jsx
- client/src/components/NavBar/NavBar.module.css
- client/src/components/NavBar/ppruebita.txt
Added some features tu navbar for better UX
> Products cards and Nav Bar feautures

- client/package-lock.json
- client/src/App.jsx
- client/src/components/Product/Product.jsx
- client/src/components/Products/Products.jsx
change category por categorysid
> cards design

- api/src/controllers/categories/allCategories.js
- api/src/controllers/products/allProducts.js
- api/src/routes/categories.js
- api/src/routes/index.js
- api/src/routes/products.js
Creación de las rutas para obtener todos los productos y las categorias
> create routes get all products and categories

- README.md
Se actualiza el documento readme para iniciar con el servidor local
> Update readme for init api

- client/src/components/Filters/Filters.jsx
- client/src/components/Filters/Filters.module.css
- client/src/components/Paginate/Paginate.jsx
- client/src/components/Product/Product.module.css
- client/src/components/Products/Products.jsx
- client/src/components/Products/Products.module.css
- client/src/redux/action.js
- client/src/redux/actionType.js
- client/src/redux/reducer.js
added filters with logic only in front end, added filters component, fetch all real products data from db, successful conection.
> filters products

- api/.env.example
- api/package-lock.json
- api/package.json
- api/src/config/firebase.js
- api/src/config/multer.js
- api/src/controllers/users/createUser.js
- api/src/routes/index.js
- api/src/routes/products.js
- api/src/routes/users.js
- api/src/utils/uploadFile.js
Se agrego funcionalidad para carga de imagenes a firebase y ruta de prueba post para users
> Upload image firebase and test create user route

- api/src/controllers/products/detailProduct.js
- api/src/routes/products.js
Se crea la ruta para obtener el detalle por producto, endpoint: localhost:3001/products/1
> Create get detail product route

- client/src/App.jsx
- client/src/LandingPage/LandingPage.jsx
- client/src/LandingPage/LandingPage.module.css
- client/src/components/About/About.jsx
- client/src/components/About/About.module.css
- client/src/components/NavBar/NavBar.jsx
Falta corregir landing, estoy en proceso y los filtros
> corrigiendo about rutas y landing

- api/src/controllers/products/newProduct.js
- api/src/controllers/users/createUser.js
- api/src/routes/products.js
- api/src/utils/categories.json
- api/src/utils/products.json
- api/src/utils/uploadFile.js
Implementación del endpoint localhost:3001/products con el metodo post para crear productos y se modificaron algunas imagenes de referencia en los utils
> Add create product route

- client/package-lock.json
- client/src/components/Filters/Filters.jsx
- client/src/components/Paginate/Paginate.jsx
- client/src/components/Paginate/Paginate.module.css
> DESIGNING BUGS

- client/src/components/Products/Products.jsx
- client/src/components/Products/Products.module.css
- client/src/components/SearchBar/SearchBar.jsx
- client/src/components/SearchBar/SearchBar.modules.css
En esta revisión del componente, he adoptado un enfoque diferente para implementar la funcionalidad. Para mantener la coherencia sintáctica con otros componentes, hemos migrado de una Declaración de Función, que capitaliza el hoisting y aprovecha la estructura dimensional de la función, hacia una Expresión de Función Flecha. Esta transición se debe a que la expresión de función flecha ofrece una solución más concisa para esta funcionalidad específica.
> Branch search bar

- client/src/components/Paginate/Paginate.jsx
- client/src/components/Paginate/Paginate.module.css
- client/src/components/footer/Footer.jsx
correcccion paginate y footer link about y contact
> correecion paginate

- api/src/controllers/products/deleteProduct.js
- api/src/controllers/products/detailProduct.js
- api/src/controllers/products/updateProduct.js
- api/src/routes/products.js
Se agrega rutas delete y put para productos, queda pendiente actualizar ruta put por patch si es necesario
> add-routes-for-put-and-delete-products

- client/src/components/Form/Form.jsx
- client/src/components/Form/Form.module.css
- client/src/components/Form/validate.js
No se actualiza el estado  de imagen
> Form, esta bug la imagen

- client/src/components/Form/Form.jsx
Se corrigen detalles al momento de seleccionar una imagen
> fix-input-image

- client/src/components/Product/Product.module.css
> solving stars css

- api/src/controllers/products/allProducts.js
- api/src/controllers/products/detailProduct.js
- api/src/database/seeder.js
- api/src/models/Product.js
- api/src/models/User.js
- api/src/utils/reviews.json
- api/src/utils/users.json
Se agrega el seeder para reviews, y el rating por producto en la ruta allProducts y detailProduct
> add-seeder-for-reviews-and-add-rating-for-products

- api/src/controllers/filter/filterProduct.js
- api/src/controllers/products/newProduct.js
Se agrega mensaje de respuesta al crear producto, y ordenar por precio
> Update response for new product route

- client/src/components/ContactUs/ContactUs.jsx
- client/src/components/ContactUs/ContactUs.module.css
> Contact Css Change

- api/.env.example
- api/package-lock.json
- api/package.json
- api/src/controllers/orders/createOrder.js
- api/src/controllers/orders/recieveWebHook.js
- api/src/middlewares/cors.js
- api/src/routes/index.js
- api/src/routes/orders.js
Se agrega la funcionalidad en el back de mercado pago
> Mercado pago integration

- client/package-lock.json
- client/package.json
- client/src/components/ContactUs/ContactUs.jsx
- client/src/components/Form/Form.module.css
> Contact email form working

- api/src/controllers/orders/createOrder.js
- api/src/controllers/orders/recieveWebHook.js
- api/src/utils/getProduct.js
Se implementa guardar orden de compra, y actualizar stock por producto
> implement-save-order-and-detail-db-and-update-stock

- client/src/components/Detail/Detail.jsx
- client/src/components/Whislist/Whislist.jsx
- client/src/redux/action.js
- client/src/redux/actionType.js
- client/src/redux/reducer.js
> whislist  detail

- client/src/App.jsx
- client/src/components/Detail/Detail.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/Whislist/Whislist.jsx
- client/src/components/Whislist/Whislist.module.css
> whislist in detail

- client/src/components/Home/Home.jsx
- client/src/components/Home/Home.module.css
Products load fixed. Loading screen implemented
> Home Fix/Loading added

- client/src/components/Detail/Detail.jsx
- client/src/components/Product/Product.jsx
- client/src/components/Products/Products.jsx
- client/src/components/Whislist/Whislist.jsx
- client/src/components/Whislist/Whislist.module.css
> whislist product

- client/package-lock.json
- client/package.json
- client/src/components/Detail/Detail.jsx
- client/src/components/Product/Product.jsx
- client/src/components/Product/Product.module.css
Final details of shopping cart, also added some animations...
> animation button

- api/src/controllers/orders/recieveWebHook.js
- api/src/utils/emails.js
- api/src/utils/mocks/users.json
Se implementa enviar correo al aprobar una orden o rechazarla
> config-email-for-order

- client/.env
- client/package-lock.json
- client/package.json
- client/src/App.css
- client/src/components/Form/Form.jsx
- client/src/components/Login/Login.jsx
- client/src/components/NavBar/NavBar.module.css
- client/src/components/footer/Footer.jsx
- client/src/components/footer/Footer.module.css
- client/src/index.css
- client/src/redux/action.js
Se arregla el estilo del footer para que quede al final de la pagina y test con libreria para auth de terceros pendiente
> fix-footer-styles-and-test-react-social-login

- client/src/components/Login/Login.jsx
- client/src/components/SignUp/SignUp.jsx
> Autenticación

- client/src/App.jsx
- client/src/components/Login/Login.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/redux/action.js
- client/src/redux/actionType.js
- client/src/redux/reducer.js
Se incorpora login y registro en el front, y persistencia de sesión
> implement-auth-and-persist-user

- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.module.css
- client/src/components/SignUp/SignUp.jsx
- client/src/components/SignUp/SignUp.module.css
> Fix alertas del login y signup

- client/src/components/Filters/Filters.jsx
- client/src/components/Filters/Filters.module.css
- client/src/components/NavBar/NavBar.module.css
- client/src/components/Products/Products.jsx
- client/src/components/Products/Products.module.css
- client/src/components/SearchBar/SearchBar.jsx
- client/src/components/Swiper/Swiper.jsx
- client/src/components/footer/Footer.module.css
- client/src/index.css
> searchbar Redesign

- api/src/controllers/users/createUser.js
- api/src/controllers/users/loginUser.js
- api/src/middlewares/cors.js
Se actualiza la respuestas de los diferentes eventos en login y register
> Update login and cors

- client/src/components/SignUp/SignUp.jsx
> Validación SignUp

- client/src/components/Login/Login.jsx
Se arregla configuración de login con google
> fix-login-google

- api/.env.example
- api/src/controllers/orders/recieveWebHook.js
- client/.env
- client/package-lock.json
- client/src/components/Login/Login.jsx
Se arregla bug con el id del usuario recibido en mercado pago
> fix-order-and-idUser

- api/src/controllers/orders/recieveWebHook.js
- api/src/utils/mocks/users.json
- client/src/components/Home/Home.jsx
- client/src/components/Products/Products.jsx
- client/src/components/ShoppingCart/ShoppingCart.jsx
Se arregla el problema al volver de mercado pago, y se agrega modal para cuando finaliza la compra
> fix-bug-in-the-cart-and-add-modals

- client/src/components/ShoppingCart/ShoppingCart.jsx
> Calvo2244 alert

- api/src/controllers/users/createUser.js
- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.module.css
- client/src/components/Products/Products.jsx
- client/src/components/ShoppingCart/ShoppingCart.jsx
- client/src/components/SignUp/SignUp.jsx
- client/src/components/SignUp/SignUp.module.css
Se agregan alertas customizadas, loading al signup y login, y se arregla bug al crear usuario con imagen
> add-custom-alerts-and-fix-error-create-user

- client/src/components/NavBar/NavBar.module.css
- client/src/components/Products/Products.jsx
- client/src/components/Products/Products.module.css
- client/src/components/SearchBar/SearchBar.jsx
redesigning searchbar  , looking better
> searchbar responsive

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/Login/Login.jsx
- client/src/components/NavBar/NavBar.module.css
- client/src/components/ShoppingCart/ShoppingCart.jsx
- client/src/components/ShoppingCart/ShoppingCart.module.css
- client/src/components/SignUp/SignUp.jsx
Agregar JWT decode para expiración de token y estilos para shopping y logout
> add-expires-token-and-styles

- client/src/components/Whislist/Whislist.jsx
> whislist render
